name: wallet_exp
description: A Web5 Wallet
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.4.0
  flutter_hooks: ^0.18.6
  flutter_inappwebview: ^5.7.2+3
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  logging: ^1.2.0
  path_provider: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
    - assets/web5.js
    - assets/images/
