name: wallet_exp
description: A TBD test wallet
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uni_links: ^0.5.1    
  archive: ^3.3.7
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  webview_flutter: ^4.2.2
  path_provider: ^2.0.15
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
    - assets/scripts.js
    - assets/web5.js
    - assets/web5.zip
